---
#-------------------------------------------------------------------------------
# Docker development environment composition for the ereefs.github.io website
#-------------------------------------------------------------------------------
volumes:
  jekyll-cache:
  jekyll-site:

services:
  ereefs-github-io:
    build: .
    image: ereefs/ereefs-github-io
    container_name: ereefs-github-io
    volumes:
      - ./docs/:/srv/jekyll/
      - ./start-jekyll-server.sh:/start-jekyll-server.sh
      - jekyll-cache:/srv/jekyll/.jekyll-cache
      - jekyll-site:/srv/jekyll/_site
    ports:
      - "4000:4000"
      - "35729:35729"
    entrypoint:
      bash
    command:
      /start-jekyll-server.sh
