aux_links_new_tab: true
aux_links: {}
back_to_top: true
back_to_top_text: "Back to top"
description: "Landing page for the eReefs Collaboration"
exclude: []
heading_anchors: true
last_edit_timestamp: false
markdown: kramdown
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-redirect-from
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" #, "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
atom_feed:
  hide: true
title: eReefs
logo: "/assets/images/logos/ereefs_logo.svg"
collections:
  - collaborators
  - funding
